//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbacusAPI.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.MarketingJobs = new HashSet<MarketingJob>();
        }
    
        public int Id { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public string Street { get; set; }
        public Nullable<int> SuburbId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string PostCode { get; set; }
        public bool IsDelivery { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> OrganisationId { get; set; }
        public Nullable<int> MarketingJobId { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual City City { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Country Country { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual State State { get; set; }
        public virtual Suburb Suburb { get; set; }
        public virtual ICollection<MarketingJob> MarketingJobs { get; set; }
    }
}
