//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbacusAPI.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation
    {
        public int Id { get; set; }
        public int ContactId { get; set; }
        public int OrganisationId { get; set; }
        public string ContactType { get; set; }
        public string ConversationJobNumber { get; set; }
        public string ConversationText { get; set; }
        public Nullable<bool> HasTask { get; set; }
        public bool Active { get; set; }
        public System.DateTime Created { get; set; }
        public int UserCreatedId { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Organisation Organisation { get; set; }
    }
}
