//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbacusAPI.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketingJob
    {
        public MarketingJob()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string Barcode { get; set; }
        public int OrganisationId { get; set; }
        public int ContactId { get; set; }
        public int AddressId { get; set; }
        public string Title { get; set; }
        public int ProgramId { get; set; }
        public int TypeOfRequestId { get; set; }
        public int OrderForm { get; set; }
        public bool IsSamples { get; set; }
        public bool IsPosters { get; set; }
        public System.DateTime RequestDeliveryDate { get; set; }
        public System.DateTime IndicativeOrderReturn { get; set; }
        public System.DateTime LastDayOfSchoolYear { get; set; }
        public int LogoId { get; set; }
        public string DeliveryInstructions { get; set; }
        public string Notes { get; set; }
        public bool Smencils { get; set; }
        public bool Online { get; set; }
        public int CreatedUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int SubmittedUserId { get; set; }
        public System.DateTime SubmittedDate { get; set; }
        public int JobStatus { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual Program Program { get; set; }
        public virtual TypeOfRequest TypeOfRequest { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
