//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbacusAPI.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersChangeLog
    {
        public System.Guid Id { get; set; }
        public long ImageId { get; set; }
        public string OrderType { get; set; }
        public int OldQuantity { get; set; }
        public int NewQuantity { get; set; }
        public long OldSchoolCode { get; set; }
        public long NewSchoolCode { get; set; }
        public string OldRoom { get; set; }
        public string NewRoom { get; set; }
    }
}
