//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbacusAPI.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        public Organisation()
        {
            this.Addresses = new HashSet<Address>();
            this.Contacts = new HashSet<Contact>();
            this.Conversations = new HashSet<Conversation>();
            this.InvoiceTotals = new HashSet<InvoiceTotal>();
            this.MarketingJobs = new HashSet<MarketingJob>();
            this.OrganisationDetail_InSchool = new HashSet<OrganisationDetail_InSchool>();
            this.OrganisationDetail_InSchool1 = new HashSet<OrganisationDetail_InSchool>();
        }
    
        public int Id { get; set; }
        public int Code { get; set; }
        public string Name { get; set; }
        public string Programs { get; set; }
        public string EducationID { get; set; }
        public Nullable<int> DecileId { get; set; }
        public int Roll { get; set; }
        public Nullable<int> RankId { get; set; }
        public int Classrooms { get; set; }
        public System.DateTime LastDateBasicEvent { get; set; }
        public string HaveLogo { get; set; }
        public string CustComment { get; set; }
        public string CustQuickComment { get; set; }
        public string ContactPersonalNote { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Conversation> Conversations { get; set; }
        public virtual Decile Decile { get; set; }
        public virtual ICollection<InvoiceTotal> InvoiceTotals { get; set; }
        public virtual ICollection<MarketingJob> MarketingJobs { get; set; }
        public virtual ICollection<OrganisationDetail_InSchool> OrganisationDetail_InSchool { get; set; }
        public virtual ICollection<OrganisationDetail_InSchool> OrganisationDetail_InSchool1 { get; set; }
        public virtual Rank Rank { get; set; }
    }
}
