//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbacusAPI.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganisationDetail_InSchool
    {
        public long Id { get; set; }
        public Nullable<int> CurrentSupplierCalendar_Id { get; set; }
        public Nullable<int> Organisation_Id { get; set; }
    
        public virtual Organisation Organisation { get; set; }
        public virtual Organisation Organisation1 { get; set; }
    }
}
