//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbacusAPI.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public Program()
        {
            this.MarketingJobs = new HashSet<MarketingJob>();
            this.TypeOfRequests = new HashSet<TypeOfRequest>();
        }
    
        public int Id { get; set; }
        public string IdCode { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<MarketingJob> MarketingJobs { get; set; }
        public virtual ICollection<TypeOfRequest> TypeOfRequests { get; set; }
    }
}
