//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbacusAPI.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class utContentSearch
    {
        public int nodeID { get; set; }
        public string title { get; set; }
        public string docAlias { get; set; }
        public string synopsis { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
    }
}
