//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbacusAPI.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class utOrder
    {
        public System.Guid Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int OrderNumber { get; set; }
        public int OrderStatus { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string DeliveryName { get; set; }
        public string DeliveryAddressLine1 { get; set; }
        public string DeliveryAddressLine2 { get; set; }
        public string DeliverySuburb { get; set; }
        public string DeliveryCity { get; set; }
        public string DeliveryPostCode { get; set; }
        public string DeliveryCountry { get; set; }
        public string DeliveryComments { get; set; }
        public string BillingName { get; set; }
        public string BillingAddressLine1 { get; set; }
        public string BillingAddressLine2 { get; set; }
        public string BillingSuburb { get; set; }
        public string BillingCity { get; set; }
        public string BillingPostCode { get; set; }
        public string BillingCountry { get; set; }
        public decimal PriceFreight { get; set; }
        public decimal PriceTax { get; set; }
        public bool IsConfirmationEmailSent { get; set; }
        public Nullable<System.DateTime> ShippedEmailSentDate { get; set; }
        public string ShippingTrackingNumber { get; set; }
        public string ShippingTrackingURL { get; set; }
        public string PaymentGatewayReference { get; set; }
        public string PromoCode { get; set; }
        public bool OptOutEMarketing { get; set; }
        public System.Guid SchoolId { get; set; }
        public string AdditionalSchools { get; set; }
        public string Currency { get; set; }
        public string Website { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<bool> IsReorder { get; set; }
        public string SchoolCode1 { get; set; }
        public string SchoolName1 { get; set; }
        public string SchoolCode2 { get; set; }
        public string SchoolName2 { get; set; }
    }
}
