//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbacusAPI.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class utPromoCode
    {
        public System.Guid Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string PromoCode { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<System.DateTime> DateValidFrom { get; set; }
        public Nullable<System.DateTime> DateValidTo { get; set; }
        public Nullable<bool> IsSingleUse { get; set; }
        public string SchoolCode { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public string QualifierProductID { get; set; }
        public Nullable<int> QualifierProductQty { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
    }
}
