//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbacusAPI.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class utSchoolGalleryImage
    {
        public System.Guid Id { get; set; }
        public string Caption { get; set; }
        public System.Guid SchoolId { get; set; }
        public int Priority { get; set; }
        public string ImageName { get; set; }
        public string LinkURL { get; set; }
    }
}
