//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbacusAPI.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class utSchool
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public bool IsPublished { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string HeaderBGColour { get; set; }
        public string MainText { get; set; }
        public string Quote1Text { get; set; }
        public string Quote1Author { get; set; }
        public string Quote2Text { get; set; }
        public string Quote2Author { get; set; }
        public string Quote3Text { get; set; }
        public string Quote3Author { get; set; }
        public string PTAMessageTitle { get; set; }
        public string PTAMessageText { get; set; }
        public string PTAMessageAuthor { get; set; }
        public string MainImageName { get; set; }
        public decimal DiscountPercentage { get; set; }
        public string DiscountPromoCode { get; set; }
        public string SPEnabledProductIds { get; set; }
        public Nullable<bool> EnableSubmitPhoto { get; set; }
        public Nullable<bool> EnableSchoolPage { get; set; }
        public string StarImageName { get; set; }
        public string Code { get; set; }
        public string HeaderBorderBottomColour { get; set; }
    }
}
