//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbacusAPI.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class utShoppingCartItem
    {
        public System.Guid Id { get; set; }
        public System.Guid ShoppingCartId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ItemType { get; set; }
        public int Quantity { get; set; }
        public int ProductId { get; set; }
        public string CustomText { get; set; }
        public string CustomImageSrc { get; set; }
        public string CustomImageAttributes { get; set; }
        public string CustomImageSrc2 { get; set; }
        public string CustomImageAttributes2 { get; set; }
        public string Rnd { get; set; }
        public Nullable<bool> SubmitPhoto { get; set; }
    }
}
