//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbacusAPI.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class utSPOrder
    {
        public System.Guid Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string OrganisationName { get; set; }
        public string Name { get; set; }
        public string PhoneArea { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string StudentName { get; set; }
        public string StudentClass { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<bool> Finalised { get; set; }
        public int OrderNumber { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
        public Nullable<bool> IsPaidToSchool { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<int> SchoolCode { get; set; }
        public string OrganisationAddress { get; set; }
        public Nullable<bool> OptOutEMarketing { get; set; }
    }
}
