//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbacusAPI.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class utSPReorderItem
    {
        public System.Guid Id { get; set; }
        public System.Guid OrderId { get; set; }
        public string ImageNumber { get; set; }
        public int QtyCalendars { get; set; }
        public int QtyDiaries { get; set; }
        public int QtyCards { get; set; }
        public Nullable<decimal> UnitPriceCalendar { get; set; }
        public Nullable<decimal> UnitPriceDiary { get; set; }
        public Nullable<decimal> UnitPriceCard { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
